### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by teod0r** [tstein/AndroSS#13]
I have samsung Galaxy TAB4 10.1 and cyanogenmod. I gave the program root permissions.
It doesn't do screenshots when I hold powerbutton and volume_down. Also I tryed to shake, but it doesn't work too.
When I hold powerbutton and volume_down or shake, there is nothing in logcat. Maybe my device doesn't react on such things.

Could you make a button in the program to take a screenshot after delay of some seconds?

**Comment by tstein** [comment]
AndroSS hasn't worked on any version of Android since Gingerbread (2.3.7). From Honeycomb (3.0) on, Google added additional protection against screen-scraping that foiled the techniques I used here, but they also added built-in screenshot functionality (normally by holding power + volume down for a few seconds, as you mentioned). I haven't worked on this since then - the system's version of screenshooting is much better, anyway. :)

Every version of Cyanogenmod I've used since then supported that standard shortcut. I can't think of any way AndroSS could be interfering, but it's definitely not helping, so you should uninstall it and try again. If that still doesn't work on your device, you may want to get in touch with whoever made your ROM.
